package res

import (
	"kar/engine/util"
	"kar/items"

	"github.com/setanarut/anim"

	"github.com/hajimehoshi/ebiten/v2"
)

var (
	AtlasPlayer  = util.LoadEbitenImageFromFS(assets, "assets/player.png")
	Border48     = util.LoadEbitenImageFromFS(assets, "assets/border48.png")
	Border32     = util.LoadEbitenImageFromFS(assets, "assets/border32.png")
	Slot16       = util.LoadEbitenImageFromFS(assets, "assets/slot16.png")
	SpriteFrames = make(map[uint16][]*ebiten.Image)
)

func init() {
	blockAtlas := util.LoadEbitenImageFromFS(assets, "assets/blocks.png")
	itemAtlas := util.LoadEbitenImageFromFS(assets, "assets/items.png")
	s := 16

	// blocks
	SpriteFrames[items.Grass] = anim.SubImages(blockAtlas, 0, 0, s, s, 11, false)
	SpriteFrames[items.Snow] = anim.SubImages(blockAtlas, 0, s, s, s, 11, false)
	SpriteFrames[items.Dirt] = anim.SubImages(blockAtlas, 0, 2*s, s, s, 11, false)
	SpriteFrames[items.Sand] = anim.SubImages(blockAtlas, 0, 3*s, s, s, 11, false)
	SpriteFrames[items.Stone] = anim.SubImages(blockAtlas, 0, 4*s, s, s, 11, false)
	SpriteFrames[items.CoalOre] = anim.SubImages(blockAtlas, 0, 5*s, s, s, 11, false)
	SpriteFrames[items.GoldOre] = anim.SubImages(blockAtlas, 0, 6*s, s, s, 11, false)
	SpriteFrames[items.IronOre] = anim.SubImages(blockAtlas, 0, 7*s, s, s, 11, false)
	SpriteFrames[items.DiamondOre] = anim.SubImages(blockAtlas, 0, 8*s, s, s, 11, false)
	SpriteFrames[items.CopperOre] = anim.SubImages(blockAtlas, 0, 9*s, s, s, 11, false)
	SpriteFrames[items.EmeraldOre] = anim.SubImages(blockAtlas, 0, 10*s, s, s, 11, false)
	SpriteFrames[items.LapisOre] = anim.SubImages(blockAtlas, 0, 11*s, s, s, 11, false)
	SpriteFrames[items.RedstoneOre] = anim.SubImages(blockAtlas, 0, 12*s, s, s, 11, false)
	SpriteFrames[items.DeepslateStone] = anim.SubImages(blockAtlas, 0, 13*s, s, s, 11, false)
	SpriteFrames[items.DeepslateCoalOre] = anim.SubImages(blockAtlas, 0, 14*s, s, s, 11, false)
	SpriteFrames[items.DeepslateGoldOre] = anim.SubImages(blockAtlas, 0, 15*s, s, s, 11, false)
	SpriteFrames[items.DeepslateIronOre] = anim.SubImages(blockAtlas, 0, 16*s, s, s, 11, false)
	SpriteFrames[items.DeepslateDiamondOre] = anim.SubImages(blockAtlas, 0, 17*s, s, s, 11, false)
	SpriteFrames[items.DeepslateCopperOre] = anim.SubImages(blockAtlas, 0, 18*s, s, s, 11, false)
	SpriteFrames[items.DeepslateEmeraldOre] = anim.SubImages(blockAtlas, 0, 19*s, s, s, 11, false)
	SpriteFrames[items.DeepslateLapisOre] = anim.SubImages(blockAtlas, 0, 20*s, s, s, 11, false)
	SpriteFrames[items.DeepslateRedStoneOre] = anim.SubImages(blockAtlas, 0, 21*s, s, s, 11, false)
	SpriteFrames[items.Log] = anim.SubImages(blockAtlas, 0, 22*s, s, s, 11, false)
	SpriteFrames[items.Leaves] = anim.SubImages(blockAtlas, 0, 23*s, s, s, 11, false)
	SpriteFrames[items.Planks] = anim.SubImages(blockAtlas, 0, 24*s, s, s, 11, false)
	SpriteFrames[items.Cobblestone] = anim.SubImages(blockAtlas, 0, 25*s, s, s, 11, false)
	SpriteFrames[items.CobbledDeepslate] = anim.SubImages(blockAtlas, 0, 26*s, s, s, 11, false)
	// items
	SpriteFrames[items.Sapling] = anim.SubImages(itemAtlas, 0, 0, s, s, 1, false)
	SpriteFrames[items.Torch] = anim.SubImages(itemAtlas, s, 0, s, s, 1, false)
	SpriteFrames[items.Coal] = anim.SubImages(itemAtlas, 2*s, 0, s, s, 1, false)
	SpriteFrames[items.RawGold] = anim.SubImages(itemAtlas, 3*s, 0, s, s, 1, false)
	SpriteFrames[items.RawIron] = anim.SubImages(itemAtlas, 4*s, 0, s, s, 1, false)
	SpriteFrames[items.Diamond] = anim.SubImages(itemAtlas, 5*s, 0, s, s, 1, false)
	SpriteFrames[items.RawCopper] = anim.SubImages(itemAtlas, 6*s, 0, s, s, 1, false)
	SpriteFrames[items.CharCoal] = anim.SubImages(itemAtlas, 7*s, 0, s, s, 1, false)
	SpriteFrames[items.Emerald] = anim.SubImages(itemAtlas, 8*s, 0, s, s, 1, false)
	SpriteFrames[items.LapisLazuli] = anim.SubImages(itemAtlas, 9*s, 0, s, s, 1, false)
	SpriteFrames[items.Redstone] = anim.SubImages(itemAtlas, 10*s, 0, s, s, 1, false)
	SpriteFrames[items.WoodAxe] = anim.SubImages(itemAtlas, 11*s, 0, s, s, 1, false)
	SpriteFrames[items.WoodHoe] = anim.SubImages(itemAtlas, 12*s, 0, s, s, 1, false)
	SpriteFrames[items.WoodPickaxe] = anim.SubImages(itemAtlas, 13*s, 0, s, s, 1, false)
	SpriteFrames[items.WoodShovel] = anim.SubImages(itemAtlas, 14*s, 0, s, s, 1, false)
	SpriteFrames[items.WoodSword] = anim.SubImages(itemAtlas, 15*s, 0, s, s, 1, false)
	SpriteFrames[items.StoneAxe] = anim.SubImages(itemAtlas, 16*s, 0, s, s, 1, false)
	SpriteFrames[items.StoneHoe] = anim.SubImages(itemAtlas, 17*s, 0, s, s, 1, false)
	SpriteFrames[items.StonePickaxe] = anim.SubImages(itemAtlas, 18*s, 0, s, s, 1, false)
	SpriteFrames[items.StoneShovel] = anim.SubImages(itemAtlas, 19*s, 0, s, s, 1, false)
	SpriteFrames[items.StoneSword] = anim.SubImages(itemAtlas, 20*s, 0, s, s, 1, false)
	SpriteFrames[items.GoldenAxe] = anim.SubImages(itemAtlas, 21*s, 0, s, s, 1, false)
	SpriteFrames[items.GoldenHoe] = anim.SubImages(itemAtlas, 22*s, 0, s, s, 1, false)
	SpriteFrames[items.GoldenPickaxe] = anim.SubImages(itemAtlas, 23*s, 0, s, s, 1, false)
	SpriteFrames[items.GoldenShovel] = anim.SubImages(itemAtlas, 24*s, 0, s, s, 1, false)
	SpriteFrames[items.GoldenSword] = anim.SubImages(itemAtlas, 25*s, 0, s, s, 1, false)
	SpriteFrames[items.IronAxe] = anim.SubImages(itemAtlas, 26*s, 0, s, s, 1, false)
	SpriteFrames[items.IronHoe] = anim.SubImages(itemAtlas, 27*s, 0, s, s, 1, false)
	SpriteFrames[items.IronPickaxe] = anim.SubImages(itemAtlas, 28*s, 0, s, s, 1, false)
	SpriteFrames[items.IronShovel] = anim.SubImages(itemAtlas, 29*s, 0, s, s, 1, false)
	SpriteFrames[items.IronSword] = anim.SubImages(itemAtlas, 30*s, 0, s, s, 1, false)
	SpriteFrames[items.DiamondAxe] = anim.SubImages(itemAtlas, 31*s, 0, s, s, 1, false)
	SpriteFrames[items.DiamondHoe] = anim.SubImages(itemAtlas, 0, s, s, s, 1, false)
	SpriteFrames[items.DiamondPickaxe] = anim.SubImages(itemAtlas, s, s, s, s, 1, false)
	SpriteFrames[items.DiamondShovel] = anim.SubImages(itemAtlas, 2*s, s, s, s, 1, false)
	SpriteFrames[items.DiamondSword] = anim.SubImages(itemAtlas, 3*s, s, s, s, 1, false)
	SpriteFrames[items.NetheriteAxe] = anim.SubImages(itemAtlas, 4*s, s, s, s, 1, false)
	SpriteFrames[items.NetheriteHoe] = anim.SubImages(itemAtlas, 5*s, s, s, s, 1, false)
	SpriteFrames[items.NetheritePickaxe] = anim.SubImages(itemAtlas, 6*s, s, s, s, 1, false)
	SpriteFrames[items.NetheriteShovel] = anim.SubImages(itemAtlas, 7*s, s, s, s, 1, false)
	SpriteFrames[items.NetheriteSword] = anim.SubImages(itemAtlas, 8*s, s, s, s, 1, false)
	SpriteFrames[items.NetheriteScrap] = anim.SubImages(itemAtlas, 9*s, s, s, s, 1, false)
	SpriteFrames[items.NetheriteIngot] = anim.SubImages(itemAtlas, 10*s, s, s, s, 1, false)
	SpriteFrames[items.GoldIngot] = anim.SubImages(itemAtlas, 11*s, s, s, s, 1, false)
	SpriteFrames[items.IronIngot] = anim.SubImages(itemAtlas, 12*s, s, s, s, 1, false)
	SpriteFrames[items.CopperIngot] = anim.SubImages(itemAtlas, 13*s, s, s, s, 1, false)
	SpriteFrames[items.Stick] = anim.SubImages(itemAtlas, 14*s, s, s, s, 1, false)

}
